Repository DIT112-V19/group-10, pull requests merged in 2019-05, with the labels that each got.

#69 Line obstacle avoidance
  src/Line_obstacleAvoidance/Line_obstacleAvoidance.ino
Labels: Coding

#73 Line following in master
  .gitignore
  .gitignore.txt
  carMobileApp/.gitignore
  carMobileApp/app/build.gradle
  carMobileApp/app/src/androidTest/java/com/group10app/DeviceListTest.java
  carMobileApp/app/src/main/AndroidManifest.xml
  carMobileApp/app/src/main/java/com/group10app/BluetoothService.java
  carMobileApp/app/src/main/java/com/group10app/DeviceConnection.java
  carMobileApp/app/src/main/java/com/group10app/DeviceControlActivity.java
  carMobileApp/app/src/main/java/com/group10app/DeviceList.java
  carMobileApp/app/src/main/java/com/group10app/DeviceListAdapter.java
  carMobileApp/app/src/main/java/com/group10app/DeviceScanActivity.java
  carMobileApp/app/src/main/java/com/group10app/GattAttributes.java
  carMobileApp/app/src/main/java/com/group10app/MainActivity.java
  carMobileApp/app/src/main/java/com/group10app/ManualMode.java
  carMobileApp/app/src/main/res/layout/activity_main.xml
  carMobileApp/app/src/main/res/layout/bluetooth_connection.xml
  carMobileApp/app/src/main/res/layout/gatt_services_characteristics.xml
  carMobileApp/app/src/main/res/layout/in_progress_bar.xml
  carMobileApp/app/src/main/res/layout/listitem_device.xml
  carMobileApp/app/src/main/res/menu/gatt_services.xml
  carMobileApp/app/src/main/res/menu/main.xml
  carMobileApp/app/src/main/res/values/strings.xml
  src/Line_obstacleAvoidance/Line_obstacleAvoidance.ino
Labels: Sprint #6

#75 Feature integration
  src/master/master.ino
Labels: Sprint #6

#86 Rename src/LineFollowing/LineFollowing.ino to src/onlyLineFollowing/L…
  src/onlyLineFollowing/LineFollowing.ino
Labels: ✨enhancement

#87 Rename src/obstacle_avoidance/obstacle_avoidance.ino to src/OnlyObsta…
  src/OnlyObstacleAvoidance/obstacle_avoidance.ino
Labels: ✨enhancement
